name: Build flatpak
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15-23.08
      options: --privileged
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: palette.flatpak
        manifest-path: org.kicad.KiCad.yml
        cache-key: flatpak-builder
